version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fc-be

  fc-be:
    image: fc-be:latest
    container_name: fc-be
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - MONGO_PORT=27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    command: mongod --logpath=/dev/null # --quiet
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
