version: '3.7'
services:
  nginx:
    ports:
      - "443:443"
    image: nginx:alpine
    restart: always
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - bots
      - backends

networks:
  bots:
    name: bots
  backends:
    name: backends
