version: '3.1'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fc-be

  fc-be:
    image: fc-be:latest
    container_name: fc-be
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASS=password
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - dbdata6:/data/db
    ports:
      - "27017:27017"

volumes:
  dbmongo:
