version: '3.1'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fc-be
    links:
      - fc-be

  fc-be:
    image: fc-be:latest
    container_name: fc-be
    restart: always
    environment:
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASS=password
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6-focal
    container_name: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - dbmongo:/data/db
    ports:
      - "27017:27017"

volumes:
  dbmongo:
