version: '3.5'
services:
  cvw-be:
    image: cvw-be:latest
    container_name: cvw-be
    environment:
      - MONGO_PORT=27018
      - MONGO_USER=admin
      - MONGO_PASS=password
      - MONGO_HOST=cvw-mongodb
    networks:
      - cvw
    depends_on:
      - cvw-mongodb

  cvw-mongodb:
    image: mongo:6-focal
    container_name:  cvw-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27018:27017'
    volumes:
      - dbdata-worship-shedule:/data/db
    networks:
      - cvw

volumes:
  dbdata-worship-shedule:

networks:
  cvw:
    name: cvw
    driver: bridge
